const { test, expect } = require('@playwright/test');
test('Functions is entry 08 and its stack supports stepping, unwinding and zero', async ({ page }) => {
  await page.goto('/index.html?lang=en&code=c');
  const card = page.locator('.cards article').filter({ has: page.locator('h2', { hasText: /^Functions$/ }) });
  await expect(card.locator('.number')).toHaveText('08');
  await card.locator('a').click();
  await expect(page.locator('#functions > .topic-no')).toHaveText('08');
  await expect(page.locator('#sidebar a[aria-current=page]')).toContainText('08Functions');
  await expect(page).toHaveTitle('Functions · CodeViz');
  await expect(page.locator('.functions-lesson h2')).toHaveCount(10);
  await page.locator('#functions-n').selectOption('3');
  const next = page.locator('[data-functions-step=next]');
  for (let i = 0; i < 7; i++) await next.click();
  await expect(page.locator('.function-frames li')).toHaveCount(3);
  await expect(page.locator('.function-frames li[aria-current]')).toContainText('factorial(1)');
  while (await next.isEnabled()) await next.click();
  await expect(page.locator('#functions-stack .output')).toHaveText('6');
  await expect(page.locator('.function-frames li')).toHaveCount(0);
  await page.locator('[data-functions-step=previous]').click();
  await expect(page.locator('#functions-stack .output')).toHaveText('(no output)');
  await page.locator('[data-functions-step=previous]').click();
  await expect(page.locator('.function-frames li')).toHaveCount(1);
  await page.locator('[data-functions-step=reset]').click();
  await expect(page.locator('#functions-stack-status')).toContainText('Ready');
  await page.locator('#functions-n').selectOption('0');
  while (await next.isEnabled()) await next.click();
  await expect(page.locator('#functions-stack .output')).toHaveText('1');
});
test('Functions works in all 60 locale/language pairs and preserves editor/download payloads', async ({ page }) => {
  test.setTimeout(120000);
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  for (const locale of ['da', 'en', 'es', 'fr', 'de', 'pt', 'ar', 'ur', 'hi', 'zh']) for (const code of ['c', 'cpp', 'python', 'java', 'javascript', 'csharp']) {
    await page.goto(`/index.html?lang=${locale}&code=${code}#functions-4`);
    await expect(page.locator('#functions-4')).toBeVisible();
    await expect(page.locator('.functions-lesson')).toHaveAttribute('lang', 'en');
    await expect(page.locator('.functions-lesson')).toHaveAttribute('dir', 'ltr');
    if (locale !== 'en') await expect(page.locator('#functions > .notice')).toBeVisible();
    await page.evaluate(() => { window.CodeRunner.open = payload => { window.functionsPayload = payload; }; });
    const section = page.locator('#functions-4');
    await section.locator('summary').click();
    await section.locator('[data-functions-run]').click();
    expect(await page.evaluate(() => window.functionsPayload.codeLanguage)).toBe(code);
    const pending = page.waitForEvent('download'); await section.locator('[data-functions-download]').click();
    expect((await pending).suggestedFilename()).toBe({ c: 'functions-arguments.c', cpp: 'functions-arguments.cpp', python: 'functions-arguments.py', java: 'Main.java', javascript: 'functions-arguments.js', csharp: 'Program.cs' }[code]);
    if (code === 'c') await expect(section).toContainText('C passes every argument by value');
    if (code === 'java') await expect(section).toContainText('Java always passes arguments by value');
  }
  expect(errors).toEqual([]);
});
test('Functions quiz retry and completion persist independently per language', async ({ page }) => {
  await page.goto('/index.html?lang=en&code=c#functions-quiz');
  const quiz = page.locator('#functions-quiz');
  for (const [i, answer] of [1, 2, 3, 0, 1].entries()) await quiz.locator('fieldset').nth(i).locator('input').nth(answer).check();
  await expect(quiz.locator('.quiz-score')).toContainText('5 / 5');
  await page.locator('[data-functions-complete]').click(); await page.reload();
  await expect(page.locator('#functions-progress')).toContainText('Best: 5/5');
  await expect(page.locator('#functions-progress')).toContainText('Lesson marked complete');
  await quiz.locator('[data-quiz-retry]').click();
  await expect(quiz.locator('.quiz-score')).toContainText('0 / 5 answered');
  await page.locator('#program-language').selectOption('python');
  await expect(page.locator('#functions-progress')).toContainText('No completed quiz yet');
  await expect(page.locator('#functions-stack-status')).toContainText('Ready');
  await page.evaluate(() => localStorage.removeItem('codeviz-progress-v1')); await page.reload();
  await page.locator('#program-language').selectOption('c');
  await expect(page.locator('#functions-progress')).toContainText('Lesson not yet marked complete');
});
test('Functions mobile RTL and unavailable storage leave existing course entries intact', async ({ page }) => {
  await page.addInitScript(() => Object.defineProperty(window, 'localStorage', { get() { throw Error('blocked'); } }));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/index.html?lang=ar&code=python#functions');
  await expect(page.locator('html')).toHaveAttribute('dir', 'rtl');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.locator('[data-functions-complete]').click();
  await expect(page.locator('#functions-progress')).toContainText('page session only');
  await page.locator('#sidebar a[href$="#arrays"]').click();
  await expect(page.locator('#arrays > .topic-no')).toHaveText('07');
  await page.goto('/formatting.html?lang=en&code=c');
  await expect(page.locator('#sidebar a[href$="#functions"]')).toContainText('08Functions');
});
