'use strict';
window.ARRAYS_DATA = {
  id: 'arrays-c-en-v1',
  locales: {
    da: ['Arrays', 'Gem flere relaterede værdier og brug et indeks til at læse eller ændre et element.', 'Den detaljerede interaktive lektion er på engelsk og i C. Eksemplet nedenfor følger dit valgte programmeringssprog.'],
    en: ['Arrays', 'Store related values together and use an index to read or change one element.', 'The detailed interactive lesson is available in English and C. The example below uses your selected programming language.'],
    es: ['Arreglos', 'Almacena valores relacionados y usa un índice para leer o cambiar un elemento.', 'La lección interactiva detallada está disponible en inglés y C. El ejemplo usa el lenguaje de programación seleccionado.'],
    fr: ['Tableaux', 'Regroupez des valeurs et utilisez un indice pour lire ou modifier un élément.', 'La leçon interactive détaillée est disponible en anglais et en C. L’exemple utilise le langage de programmation sélectionné.'],
    de: ['Arrays', 'Speichere zusammengehörige Werte und lies oder ändere ein Element über seinen Index.', 'Die ausführliche interaktive Lektion ist auf Englisch und in C verfügbar. Das Beispiel verwendet die gewählte Programmiersprache.'],
    pt: ['Arrays', 'Agrupe valores relacionados e use um índice para ler ou alterar um elemento.', 'A lição interativa detalhada está disponível em inglês e C. O exemplo usa a linguagem de programação selecionada.'],
    ar: ['المصفوفات', 'اجمع القيم المرتبطة واستخدم فهرسًا لقراءة عنصر أو تغييره.', 'الدرس التفاعلي المفصل متاح باللغة الإنجليزية ولغة C. يستخدم المثال لغة البرمجة التي اخترتها.'],
    ur: ['ارے', 'متعلقہ قدریں اکٹھی رکھیں اور کسی عنصر کو پڑھنے یا بدلنے کے لیے انڈیکس استعمال کریں۔', 'تفصیلی تعاملی سبق انگریزی اور C میں دستیاب ہے۔ مثال آپ کی منتخب کردہ پروگرامنگ زبان استعمال کرتی ہے۔'],
    hi: ['ऐरे', 'संबंधित मानों को साथ रखें और किसी तत्व को पढ़ने या बदलने के लिए इंडेक्स का उपयोग करें।', 'विस्तृत इंटरैक्टिव पाठ अंग्रेज़ी और C में उपलब्ध है। उदाहरण आपकी चुनी हुई प्रोग्रामिंग भाषा में है।'],
    zh: ['数组', '将相关的值放在一起，通过索引读取或修改一个元素。', '详细的交互式课程目前提供英语和 C 语言版本。示例使用您选择的编程语言。']
  },
  examples: {
    c: { note: 'C arrays have a fixed length during their lifetime and contiguous elements of one type. Keep every access within 0 through count − 1.', code: '#include <stdio.h>\n\nint main(void) {\n    int values[] = {4, 8, 12, 16, 20};\n    size_t count = sizeof values / sizeof values[0];\n    values[2] = 99;\n    for (size_t i = 0; i < count; ++i) {\n        printf("%d\\n", values[i]);\n    }\n    printf("count = %zu\\n", count);\n    return 0;\n}\n' },
    cpp: { note: 'This C++ example uses std::array<int, 5>, a fixed-size container. size() reports its element count. at() checks the index and throws for an invalid access.', code: '#include <array>\n#include <iostream>\n\nint main() {\n    std::array<int, 5> values = {4, 8, 12, 16, 20};\n    values.at(2) = 99;\n    for (std::size_t i = 0; i < values.size(); ++i) {\n        std::cout << values.at(i) << "\\n";\n    }\n    std::cout << "count = " << values.size() << "\\n";\n}\n' },
    python: { note: 'Python uses a list here, not a C array. Lists can grow and hold mixed types; this example keeps integers. len() gives the count, and an invalid positive index raises IndexError.', code: 'values = [4, 8, 12, 16, 20]\nvalues[2] = 99\nfor i in range(len(values)):\n    print(values[i])\nprint(f"count = {len(values)}")\n' },
    java: { note: 'Java int[] has a fixed length, reported by .length. Integer array elements default to zero; invalid indices throw ArrayIndexOutOfBoundsException.', code: 'public class Main {\n    public static void main(String[] args) {\n        int[] values = {4, 8, 12, 16, 20};\n        values[2] = 99;\n        for (int i = 0; i < values.length; ++i) {\n            System.out.println(values[i]);\n        }\n        System.out.println("count = " + values.length);\n    }\n}\n' },
    javascript: { note: 'JavaScript arrays can grow and hold mixed types. .length is not necessarily the number of populated elements in a sparse array. Reading a missing index usually gives undefined; this example has no gaps.', code: 'const values = [4, 8, 12, 16, 20];\nvalues[2] = 99;\nfor (let i = 0; i < values.length; ++i) {\n    console.log(values[i]);\n}\nconsole.log(`count = ${values.length}`);\n' },
    csharp: { note: 'C# int[] has a fixed length, reported by .Length. Integer array elements default to zero; invalid indices throw IndexOutOfRangeException.', code: 'using System;\n\nclass Program {\n    static void Main() {\n        int[] values = {4, 8, 12, 16, 20};\n        values[2] = 99;\n        for (int i = 0; i < values.Length; ++i) {\n            Console.WriteLine(values[i]);\n        }\n        Console.WriteLine("count = " + values.Length);\n    }\n}\n' }
  },
  output: '4\n8\n99\n16\n20\ncount = 5\n',
  questions: [
    { prompt: 'Which index selects the first element of a C array?', options: ['0', '1', 'The array length', '−1'], answer: 0, explanation: 'Indexing starts at zero. For five elements, the valid indices are 0, 1, 2, 3, and 4.' },
    { prompt: 'What does this print?', code: 'int scores[5] = {4, 8};\nprintf("%d\\n", scores[4]);', options: ['8', '0', '4', 'An unknown value'], answer: 1, explanation: 'With an initializer list, any elements not explicitly listed are initialized to zero. This differs from an uninitialized local array.' },
    { prompt: 'What does this print after the update?', code: 'int values[] = {4, 8, 12};\nvalues[1] = 30;\nprintf("%d\\n", values[1]);', options: ['4', '8', '12', '30'], answer: 3, explanation: 'Assignment replaces the element at index 1, the second position. The new value is 30.' },
    { prompt: 'Which condition visits all five elements safely when i starts at zero?', options: ['i <= 5', 'i < 5', 'i > 5', 'i == 5'], answer: 1, explanation: 'i < 5 visits indices 0 through 4. i <= 5 also tries index 5, which is outside this array.' },
    { prompt: 'What does sizeof values / sizeof values[0] report for this declaration?', code: 'int values[5] = {4, 8, 12, 16, 20};', options: ['Always 20 bytes', 'The number of initialized nonzero values', '5 elements', 'The first element'], answer: 2, explanation: 'Divide the whole array’s byte size by one element’s byte size. It works here because values is the actual array, not a function parameter adjusted to a pointer.' }
  ],
  exercises: [
    { id: 'array-sum', title: 'Total five readings', problem: 'Store 3, 6, 9, 12, and 15 in an int array. Visit every element with a for loop and print their sum. Then try {0, 0, 0, 0, 0}: the sum should be 0.', expected: 'sum = 45\n', hint: 'Start sum at 0 outside the loop. Add values[i] while i < count.', starter: '#include <stdio.h>\n\nint main(void) {\n    int values[] = {3, 6, 9, 12, 15};\n    // TODO: traverse values, calculate their sum, and print it.\n    return 0;\n}\n', solution: '#include <stdio.h>\n\nint main(void) {\n    int values[] = {3, 6, 9, 12, 15};\n    size_t count = sizeof values / sizeof values[0];\n    int sum = 0;\n    for (size_t i = 0; i < count; ++i) {\n        sum += values[i];\n    }\n    printf("sum = %d\\n", sum);\n    return 0;\n}\n' },
    { id: 'array-reverse', title: 'Print in reverse order', problem: 'Print the elements {3, 6, 9, 12, 15} from last to first, one per line. Keep the stored values unchanged. No keyboard input is needed.', expected: '15\n12\n9\n6\n3\n', hint: 'Start a signed int index at 4, continue while i >= 0, and decrement it. An unsigned counter cannot become negative.', starter: '#include <stdio.h>\n\nint main(void) {\n    int values[] = {3, 6, 9, 12, 15};\n    // TODO: print elements from index 4 down to index 0.\n    return 0;\n}\n', solution: '#include <stdio.h>\n\nint main(void) {\n    int values[] = {3, 6, 9, 12, 15};\n    for (int i = 4; i >= 0; --i) {\n        printf("%d\\n", values[i]);\n    }\n    return 0;\n}\n' }
  ]
};
