'use strict';
(() => {
const D=window.COURSE_DATA, ALL_EXAMPLES=window.LANGUAGE_EXAMPLES;
let codeLanguage="python";
try { const saved=localStorage.getItem("ds-code"); if(Object.hasOwn(D.programs,saved))codeLanguage=saved; } catch {}
const queryCode=new URLSearchParams(location.search).get("code");if(Object.hasOwn(D.programs,queryCode))codeLanguage=queryCode;
let E=ALL_EXAMPLES[codeLanguage];
const program=()=>D.programs[codeLanguage];
const M=window.ModuleOne;
const filename=id=>program().filename||id+"."+program().ext;
const SITE_TITLE='Learn programming with Visualization';
const topicCount=D.topics.length+(window.ARRAYS_DATA?1:0)+(window.SWITCH_DATA?1:0)+(window.FUNCTIONS_DATA?1:0)+(window.POINTERS_DATA?1:0)+(window.OOP_DATA?1:0)+(window.FILE_HANDLING_DATA?1:0)+(window.EXCEPTION_HANDLING_DATA?1:0)+(window.UNIT_TESTING_DATA?1:0);
const switchTitle=()=>window.SWITCH_DATA?.locales[language][0]||'Switch statement';
const functionsTitle=()=>window.FUNCTIONS_DATA?.locales[language][0]||'Functions';
const arraysTitle=()=>window.ARRAYS_DATA?.locales[language][0]||'Arrays';
const pointersTitle=()=>window.POINTERS_DATA?.locales[language][0]||'Pointers';
const oopTitle=()=>window.OOP_DATA?.locales[language][0]||'Object-Oriented Programming';
const fileHandlingTitle=()=>window.FILE_HANDLING_DATA?.locales[language][0]||'File Handling';
const exceptionHandlingTitle=()=>window.EXCEPTION_HANDLING_DATA?.locales[language][0]||'Exception Handling';
const unitTestingTitle=()=>window.UNIT_TESTING_DATA?.locales[language][0]||'Unit Testing';
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rich=s=>esc(s).replace(/`([^`]+)`/g,'<code dir="ltr">$1</code>');
const groups=[[0,8],[8,15],[15,23],[23,29]], names=['intro','data','control','module-loops'];
const isReference=document.body.dataset.page==='reference';
let language='da';
try{const saved=localStorage.getItem('ds-language');if(Object.hasOwn(D.locales,saved))language=saved;}catch{}
const urlLang=new URLSearchParams(location.search).get('lang');if(Object.hasOwn(D.locales,urlLang))language=urlLang;
let module=-1,helloStep=0,operandA=7,operandB=2,truthA=1,truthB=0,score=72,limit=5,loopStep=0,demo=0,revealed=false;
let selectedExamples=['hello','arithmetic','selection','loops'];
const tr=()=>D.translations[language];
const u=key=>{if(!(key in tr().ui))throw new Error('Missing translation: '+key);return tr().ui[key];};
const link=path=>path+(path.includes('?')?'&':'?')+'lang='+encodeURIComponent(language)+'&code='+encodeURIComponent(codeLanguage);
function pageLink(path,hash=''){return link(path)+(hash?'#'+hash:'');}
function topicLink(i){return pageLink('index.html',D.topics[i]);}
function btn(key,action,extra=''){return `<button type="button" data-action="${action}" ${extra}>${esc(u(key))}</button>`;}
function codeButtons(id){return `<div class="controls"><button type="button" data-run="${id}">▶ ${esc(M.ui(language,"runner"))}</button><button type="button" data-copy="${id}">${esc(u('copy'))}</button><button type="button" data-download="${id}">${esc(u('download'))}</button></div>`;}
function fullExample(id,title){const ex=E[id];return `<details class="sample"><summary>${esc(u('code'))} · ${esc(title)}</summary>${codeButtons(id)}<pre tabindex="0" dir="ltr"><code>${esc(ex.code)}</code></pre>${ex.stdin?`<p class="small">${esc(u('input'))}</p><pre class="output" dir="ltr">${esc(ex.stdin)}</pre>`:''}${ex.output?`<p class="small">${esc(u('output'))}</p><pre class="output" dir="ltr">${esc(ex.output)}</pre>`:''}</details>`;}
function exercise(index){return `<section class="exercise"><h2>${esc(u('exercise'))}</h2><p>${esc(tr().questions[index])}</p><details><summary>${esc(u('answer'))}</summary><p>${esc(tr().answers[index])}</p></details></section>`;}
function footer(){return `<footer class="foot"><p>${esc(u('codeNote'))}</p><a href="${esc(program().docs)}" target="_blank" rel="noopener">${esc(u('source'))}</a></footer>`;}
function referenceCallout(){return `<section class="callout"><div><h2>${esc(u('reference'))}</h2><p class="small">${esc(u('referenceIntro'))}</p></div><a class="button primary" href="${pageLink('formatting.html')}">${esc(u('open'))} →</a></section>`;}
function renderShell(){
 document.documentElement.lang=language==='zh'?'zh-Hans':language;
 document.documentElement.dir=['ar','ur'].includes(language)?'rtl':'ltr';
 document.title=(isReference?u('reference'):module<0?SITE_TITLE:module===12?unitTestingTitle():module===11?exceptionHandlingTitle():module===10?fileHandlingTitle():module===9?oopTitle():module===8?pointersTitle():module===7?functionsTitle():module===6?arraysTitle():tr().modules[module])+' · CodeViz';
 $('skip').textContent=u('skip');
 $('sidebar').innerHTML=`<a class="brand" href="${pageLink('index.html')}"><span aria-hidden="true">&lt;/&gt;</span>CodeViz</a><p class="aside-note">6 ${esc(u('programLanguage'))} · ${topicCount} ${esc(u('topics'))}</p><nav aria-label="${esc(u('topics'))}"><a href="${pageLink('index.html')}" ${!isReference&&module<0?'aria-current="page"':''}><b>⌂</b>${esc(u('home'))}</a>${names.map((n,i)=>`<a href="${pageLink('index.html',n)}" ${!isReference&&module===i?'aria-current="page"':''}><b>0${i+1}</b>${esc(tr().modules[i])}</a>`).join('')}<a href="${pageLink('formatting.html')}" ${isReference?'aria-current="page"':''}><b>05</b>${esc(u('reference'))}</a><a href="${pageLink('datastrukturer.html')}"><b>06</b>${esc(u('structures'))}</a>${window.ARRAYS_DATA?`<a href="${pageLink('index.html','arrays')}" ${!isReference&&module===6?'aria-current="page"':''}><b>07</b>${esc(arraysTitle())}</a>`:''}${window.FUNCTIONS_DATA?`<a href="${pageLink('index.html','functions')}" ${!isReference&&module===7?'aria-current="page"':''}><b>08</b>${esc(functionsTitle())}</a>`:''}${window.POINTERS_DATA?`<a href="${pageLink('index.html','pointers')}" ${!isReference&&module===8?'aria-current="page"':''}><b>09</b>${esc(pointersTitle())}</a>`:''}${window.OOP_DATA?`<a href="${pageLink('index.html','oop')}" ${!isReference&&module===9?'aria-current="page"':''}><b>10</b>${esc(oopTitle())}</a>`:''}${window.FILE_HANDLING_DATA?`<a href="${pageLink('index.html','file-handling')}" ${!isReference&&module===10?'aria-current="page"':''}><b>11</b>${esc(fileHandlingTitle())}</a>`:''}${window.EXCEPTION_HANDLING_DATA?`<a href="${pageLink('index.html','exception-handling')}" ${!isReference&&module===11?'aria-current="page"':''}><b>12</b>${esc(exceptionHandlingTitle())}</a>`:''}${window.UNIT_TESTING_DATA?`<a href="${pageLink('index.html','unit-testing')}" ${!isReference&&module===12?'aria-current="page"':''}><b>13</b>${esc(unitTestingTitle())}</a>`:''}</nav>`;
 $('top').innerHTML=`<div class="controls" style="margin-inline-start:auto"><label for="program-language">${esc(u('programLanguage'))}</label><select id="program-language">${Object.entries(D.programs).map(([key,p])=>`<option value="${key}" ${key===codeLanguage?'selected':''}>${esc(p.label)}</option>`).join('')}</select><label for="language">${esc(u('language'))}</label><select id="language">${Object.entries(D.locales).map(([k,v])=>`<option value="${k}" ${k===language?'selected':''}>${esc(v)}</option>`).join('')}</select>${btn('print','print')}</div>`;
 $('program-language').addEventListener('change',e=>{
   codeLanguage=e.target.value; E=ALL_EXAMPLES[codeLanguage];
   try{localStorage.setItem('ds-code',codeLanguage);}catch{}
   try{const url=new URL(location.href);url.searchParams.set('code',codeLanguage);history.replaceState(null,'',url);}catch{}
   render();
 });
 $('language').addEventListener('change',e=>{
   language=e.target.value;
   try{localStorage.setItem('ds-language',language);}catch{}
   try{const url=new URL(location.href);url.searchParams.set('lang',language);history.replaceState(null,'',url);}catch{}
   render();
 });
}
function homeResources(){return `<article class="card"><span class="number">05</span><h2>${esc(u('reference'))}</h2><p class="small">${esc(u('referenceIntro'))}</p><ol><li><a href="${pageLink('formatting.html','escapes')}">${esc(u('escapes'))}</a></li><li><a href="${pageLink('formatting.html','formats')}">${esc(u('formats'))}</a></li></ol><a class="button" href="${pageLink('formatting.html')}">${esc(u('open'))} →</a></article><article class="card"><span class="number">06</span><h2>${esc(u('structures'))}</h2><a class="button" href="${pageLink('datastrukturer.html')}">${esc(u('open'))} →</a></article>${window.ARRAYS_DATA?`<article class="card"><span class="number">07</span><h2>${esc(arraysTitle())}</h2><p>${esc(window.ARRAYS_DATA.locales[language][1])}</p><a class="button" href="${pageLink('index.html','arrays')}">${esc(u('open'))} →</a></article>`:''}${window.FUNCTIONS_DATA?`<article class="card"><span class="number">08</span><h2>${esc(functionsTitle())}</h2><p>${esc(window.FUNCTIONS_DATA.locales[language][1])}</p><a class="button" href="${pageLink('index.html','functions')}">${esc(u('open'))}</a></article>`:''}${window.POINTERS_DATA?`<article class="card"><span class="number">09</span><h2>${esc(pointersTitle())}</h2><p>${esc(window.POINTERS_DATA.locales[language][1])}</p><a class="button" href="${pageLink('index.html','pointers')}">${esc(u('open'))}</a></article>`:''}${window.OOP_DATA?`<article class="card"><span class="number">10</span><h2>${esc(oopTitle())}</h2><p>${esc(window.OOP_DATA.locales[language][1])}</p><a class="button" href="${pageLink('index.html','oop')}">${esc(u('open'))}</a></article>`:''}${window.FILE_HANDLING_DATA?`<article class="card"><span class="number">11</span><h2>${esc(fileHandlingTitle())}</h2><p>${esc(window.FILE_HANDLING_DATA.locales[language][1])}</p><a class="button" href="${pageLink('index.html','file-handling')}">${esc(u('open'))}</a></article>`:''}${window.EXCEPTION_HANDLING_DATA?`<article class="card"><span class="number">12</span><h2>${esc(exceptionHandlingTitle())}</h2><p>${esc(window.EXCEPTION_HANDLING_DATA.locales[language][1])}</p><a class="button" href="${pageLink('index.html','exception-handling')}">${esc(u('open'))}</a></article>`:''}${window.UNIT_TESTING_DATA?`<article class="card"><span class="number">13</span><h2>${esc(unitTestingTitle())}</h2><p>${esc(window.UNIT_TESTING_DATA.locales[language][1])}</p><a class="button" href="${pageLink('index.html','unit-testing')}">${esc(u('open'))}</a></article>`:''}`;}
function overview(){return `<section class="hero"><h1>${esc(SITE_TITLE)}</h1><p class="lede">${esc(u('intro'))}</p><div class="tags"><span class="tag">4 ${esc(u('module'))}</span><span class="tag">${topicCount} ${esc(u('topics'))}</span><span class="tag">10 ${esc(u('language'))}</span><span class="tag">6 ${esc(u('programLanguage'))}</span></div></section><section aria-label="${esc(u('allTopics'))}" class="cards">${groups.map(([start,end],m)=>`<article class="card"><span class="number">0${m+1}</span><h2>${esc(tr().modules[m])}</h2><ol>${tr().topics.slice(start,end).map(([title],j)=>`<li><a href="${topicLink(start+j)}">${esc(title)}</a></li>${start+j===21&&window.SWITCH_DATA?`<li><a href="${pageLink('index.html','switch')}">${esc(switchTitle())}</a></li>`:''}`).join('')}</ol><a class="button" href="${pageLink('index.html',names[m])}">${esc(u('open'))} →</a></article>`).join('')}${homeResources()}</section>${footer()}`;}
const topicExamples={6:'hello',8:'memory',11:'input',13:'arithmetic',17:'truth',21:'selection',22:'assignment',24:'loops',25:'sentinel',26:'jump',27:'increment',28:'while'};
function functionsLesson(){return window.FunctionsLesson?`<article class="lesson" id="functions"><span class="topic-no">08</span><h1><a href="#functions">${esc(functionsTitle())}</a></h1><p>${esc(window.FUNCTIONS_DATA.locales[language][1])}</p>${window.FunctionsLesson.render({language,codeLanguage})}</article>`:'';}
function arrayLesson(){return window.ArraysLesson?`<article class="lesson" id="arrays"><span class="topic-no">07</span><h1><a href="#arrays">${esc(arraysTitle())}</a></h1><p>${esc(window.ARRAYS_DATA.locales[language][1])}</p>${window.ArraysLesson.render({language,codeLanguage})}</article>`:'';}
function pointersLesson(){return window.PointersLesson?`<article class="lesson" id="pointers"><span class="topic-no">09</span><h1><a href="#pointers">${esc(pointersTitle())}</a></h1><p>${esc(window.POINTERS_DATA.locales[language][1])}</p>${window.PointersLesson.render({language,codeLanguage})}</article>`:'';}
function oopLesson(){return window.OOPLesson?`<article class="lesson" id="oop"><span class="topic-no">10</span><h1><a href="#oop">${esc(oopTitle())}</a></h1><p>${esc(window.OOP_DATA.locales[language][1])}</p>${window.OOPLesson.render({language,codeLanguage})}</article>`:'';}
function fileHandlingLesson(){return window.FileHandlingLesson?`<article class="lesson" id="file-handling"><span class="topic-no">11</span><h1><a href="#file-handling">${esc(fileHandlingTitle())}</a></h1><p>${esc(window.FILE_HANDLING_DATA.locales[language][1])}</p>${window.FileHandlingLesson.render({language,codeLanguage})}</article>`:'';}
function exceptionHandlingLesson(){return window.ExceptionHandlingLesson?`<article class="lesson" id="exception-handling"><span class="topic-no">12</span><h1><a href="#exception-handling">${esc(exceptionHandlingTitle())}</a></h1><p>${esc(window.EXCEPTION_HANDLING_DATA.locales[language][1])}</p>${window.ExceptionHandlingLesson.render({language,codeLanguage})}</article>`:'';}
function unitTestingLesson(){return window.UnitTestingLesson?`<article class="lesson" id="unit-testing"><span class="topic-no">13</span><h1><a href="#unit-testing">${esc(unitTestingTitle())}</a></h1><p>${esc(window.UNIT_TESTING_DATA.locales[language][1])}</p>${window.UnitTestingLesson.render({language,codeLanguage})}</article>`:'';}
function switchLesson(){return window.SwitchLesson?`<article class="lesson" id="switch"><span class="topic-no">3.8</span><h2><a href="#switch">${esc(switchTitle())}</a></h2><p>${esc(window.SWITCH_DATA.locales[language][1])}</p>${window.SwitchLesson.render({language,codeLanguage})}</article>`:'';}
function modulePage(){const [start,end]=groups[module];return `<section class="hero"><div class="eyebrow">${esc(u('module'))} 0${module+1}</div><h1>${esc(tr().modules[module])}</h1><p class="lede" ${module===0?'hidden':''}>${esc(u('intro'))}</p>${module===0?M.hero():''}</section>${module===0?'':'<div id="labMount"></div>'}<section class="lessons" aria-label="${esc(u('topics'))}">${tr().topics.slice(start,end).map(([title,body],j)=>{const i=start+j,id=D.topics[i];let extra='';if(i===5)extra=`<p><strong>${esc(u('run'))}: ${esc(program().requires)}</strong></p><p>${esc(u('saveAs'))}: <code>${esc(filename('hello'))}</code></p><pre class="output" dir="ltr"><code>${esc(program().commands)}</code></pre>`;if(i===7)extra=`<a class="button primary" href="${pageLink('formatting.html')}">${esc(u('reference'))} →</a>`;if(i===10)extra=`<p class="notice">${esc(u('memoryNote'))}</p>`;if(i===11)extra=`<p class="notice">${rich(u('safeInput'))}</p>`;if(i===20)extra=flowchart();return `<article class="lesson" id="${id}"><span class="topic-no">${module+1}.${j+1+(module===2&&i>21&&window.SWITCH_DATA?1:0)}</span><h2><a href="#${id}">${esc(title)}</a></h2><p>${rich(body)}</p>${extra}${i===24&&window.ForLesson?window.ForLesson.render({language,codeLanguage}):''}${module===0?M.extra(i):''}${topicExamples[i]?fullExample(topicExamples[i],title):''}</article>${i===21?switchLesson():''}`;}).join('')}</section>${exercise(module)}${module===0||module===1?referenceCallout():''}<div class="pager">${module>0?`<a class="button" href="${pageLink('index.html',names[module-1])}">← ${esc(tr().modules[module-1])}</a>`:`<a class="button" href="${pageLink('index.html')}">← ${esc(u('home'))}</a>`}${module<3?`<a class="button primary" href="${pageLink('index.html',names[module+1])}">${esc(tr().modules[module+1])} →</a>`:''}</div>${footer()}`;}
function flowchart(){const pass=score>=50;return `<svg class="flow" viewBox="0 0 400 360" role="img" aria-label="${esc(tr().topics[20][0]+': '+u('score')+' >= 50')}"><defs><marker id="arrow-${module}" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6" fill="#7187a1"/></marker></defs><g class="arrow" marker-end="url(#arrow-${module})"><path d="M200 48 V75"/><path d="M200 161 V183 H95 V215"/><path d="M200 161 V183 H305 V215"/><path d="M95 255 V296 H200 V313"/><path d="M305 255 V296 H200"/></g><rect class="node" x="150" y="8" width="100" height="40" rx="20"/><text x="200" y="34" text-anchor="middle">${esc(u('start'))}</text><polygon class="decision" points="200,75 287,118 200,161 113,118"/><text x="200" y="123" text-anchor="middle">score ≥ 50?</text><text x="92" y="203" text-anchor="middle">${esc(u('true'))}</text><text x="308" y="203" text-anchor="middle">${esc(u('false'))}</text><rect class="node ${pass?'active-node':''}" x="25" y="215" width="140" height="40" rx="4"/><text x="95" y="241" text-anchor="middle">${esc(u('pass'))}</text><rect class="node ${!pass?'active-node':''}" x="235" y="215" width="140" height="40" rx="4"/><text x="305" y="241" text-anchor="middle">${esc(u('retry'))}</text><rect class="node" x="150" y="313" width="100" height="40" rx="20"/><text x="200" y="339" text-anchor="middle">${esc(u('end'))}</text></svg>`;}
function currentCode(id){return (E[id].template||E[id].code).replaceAll('@A@',operandA).replaceAll('@B@',operandB).replaceAll('@SCORE@',score).replaceAll('@LIMIT@',limit);}

function currentId(){return isReference?'format'+demo:selectedExamples[module];}
function codePane(){const id=currentId();
 const lines=currentCode(id).trimEnd().split('\n');return `<div class="code-pane"><div class="code-head"><h3>${esc(u('code'))} · ${esc(program().label)} · ${esc(filename(id))}</h3>${codeButtons('current')}</div><pre id="codeView" tabindex="0" dir="ltr"><code>${lines.map((line,i)=>`<span class="code-line ${module===0&&!isReference&&i===E.hello.trace[helloStep]?'active':''}"><span class="line-num">${i+1}</span>${esc(line)||' '}</span>`).join('')}</code></pre><p class="small">${esc(u('codeNote'))}</p></div>`;
}
function arithmeticResult(){
 if(!validOperands())return u('rangeError');
 const fractional=['python','javascript'].includes(codeLanguage);
 const numberText=n=>codeLanguage==='javascript'&&Object.is(n,-0)?'-0':String(n);
 let quotient=fractional?numberText(operandA/operandB):String(Math.trunc(operandA/operandB));
 if(codeLanguage==='python'&&Number.isInteger(operandA/operandB))quotient=(Object.is(operandA/operandB,-0)?'-0':quotient)+'.0';
 const remainder=codeLanguage==='python'?((operandA%operandB)+operandB)%operandB:operandA%operandB;
 return `+ : ${numberText(operandA+operandB)}\n- : ${numberText(operandA-operandB)}\n* : ${numberText(operandA*operandB)}\n/ : ${quotient}\n% : ${numberText(remainder)}\n${codeLanguage==='python'?'// : '+Math.floor(operandA/operandB)+'\n':''}7.0 / 2 = 3.50\n2 + 3 * 4 = 14\n(2 + 3) * 4 = 20\n`;
}

function validOperands(){return [operandA,operandB].every(x=>Number.isInteger(x)&&Math.abs(x)<=100)&&operandB!==0;}
function truthTable(){return `<div class="table-wrap"><table class="truth-table"><caption>${esc(tr().topics[17][0])}</caption><thead><tr>${(codeLanguage==='python'?['a','b','a and b','a or b','not a']:['a','b','a && b','a || b','!a']).map(s=>`<th scope="col"><code>${esc(s)}</code></th>`).join('')}</tr></thead><tbody>${[[0,0],[0,1],[1,0],[1,1]].map(([a,b])=>`<tr class="${a===truthA&&b===truthB?'chosen':''}"><td>${a}</td><td>${b}</td><td>${a&&b?1:0}</td><td>${a||b?1:0}</td><td>${a?0:1}</td></tr>`).join('')}</tbody></table></div>`;}
function stage(){
 if(isReference)return `<label for="demoSelect">${esc(u('select'))}</label><select id="demoSelect" dir="ltr">${Object.keys(E).filter(k=>k.startsWith('format')).map((k,i)=>`<option value="${i}" ${i===demo?'selected':''}>${esc(E[k].label)}</option>`).join('')}</select><p>${esc(tr().topics[7][1].replace(/`/g,''))}</p><div class="controls">${btn('reveal','reveal','class="primary"')}${btn('reset','reset')}</div><h3>${esc(u('output'))}</h3><div id="demoOutput" aria-live="polite">${revealed?`<pre class="output" dir="ltr">${esc(E[currentId()].output)}</pre>`:`<div class="placeholder">${esc(u('reveal'))} →</div>`}</div>`;
 if(module===0)return `<p class="eyebrow">Hello, world!</p><div class="metrics"><div class="metric"><span>${esc(u('next'))}</span><strong>${helloStep+1} / 3</strong></div></div><p>${rich(tr().topics[6][1])}</p><div class="controls">${btn('next','step',`class="primary" ${helloStep===2?'disabled':''}`)}${btn('reset','reset')}</div><h3>${esc(u('output'))}</h3><pre class="output" dir="ltr" aria-live="polite">${helloStep>=1?'Hello, world!\n':'—'}</pre>`;
 if(module===1)return `<p>${rich(tr().topics[13][1])}</p><div class="controls"><label for="operandA">a</label><input id="operandA" type="number" min="-100" max="100" step="1" value="${operandA}"><label for="operandB">b</label><input id="operandB" type="number" min="-100" max="100" step="1" value="${operandB}">${btn('reset','reset')}</div><p class="small">${esc(u('rangeError'))}</p><h3>${esc(u('output'))}</h3><pre id="arithmeticOutput" class="output" dir="ltr" aria-live="polite">${esc(arithmeticResult())}</pre><p class="small">${esc(u('memoryNote'))}</p>`;
 if(module===2)return `<div class="controls"><label for="truthA">a</label><select id="truthA">${[0,1].map(n=>`<option value="${n}" ${truthA===n?'selected':''}>${n} · ${esc(u(n?'true':'false'))}</option>`).join('')}</select><label for="truthB">b</label><select id="truthB">${[0,1].map(n=>`<option value="${n}" ${truthB===n?'selected':''}>${n} · ${esc(u(n?'true':'false'))}</option>`).join('')}</select></div>${truthTable()}<div class="controls"><label for="score">${esc(u('score'))}</label><input id="score" type="range" min="0" max="100" value="${score}"><output for="score">${score}</output></div><p class="notice" aria-live="polite"><code dir="ltr">score >= 50 → ${score>=50?1:0}</code> · ${esc(u(score>=50?'pass':'retry'))}</p>`;
 return `<label for="limit">${esc(u('limit'))}</label><input id="limit" type="number" min="0" max="10" step="1" value="${limit}"><div class="metrics"><div class="metric"><span>${esc(u('iteration'))}</span><strong>${loopStep} / ${limit}</strong></div><div class="metric"><span>${esc(u('total'))}</span><strong>${loopStep*(loopStep+1)/2}</strong></div></div><div class="trace">${Array.from({length:limit},(_,i)=>`<span class="${i+1===loopStep?'current':i<loopStep?'done':''}">${i+1}</span>`).join('')}</div><div class="controls">${btn('next','step',`class="primary" ${loopStep>=limit?'disabled':''}`)}${btn('reset','reset')}</div><h3>${esc(u('output'))}</h3><pre class="output" dir="ltr" aria-live="polite">${Array.from({length:loopStep},(_,i)=>`i = ${i+1}, total = ${(i+1)*(i+2)/2}`).join('\n')||'—'}</pre><p class="small">${loopStep>=limit?esc(u('complete')):esc(tr().topics[24][0])}</p>`;
}
function renderLab(){const target=$('labMount');if(!target)return;target.innerHTML=`<section class="lab" aria-label="${esc(u('lab'))}"><div class="lab-head"><h2>${esc(u('lab'))}</h2><p class="small">${esc(u('labNote'))}</p></div><div class="lab-grid"><div class="stage">${stage()}</div>${codePane()}</div></section>`;
 const update=(id,cb)=>{const el=$(id);if(el)el.addEventListener('change',()=>{cb(el);renderLab();$(id)?.focus();});};
 update('demoSelect',e=>{demo=Number(e.value);revealed=false;});
 
 update('operandA',e=>{const n=Number(e.value);if(e.value.trim()&&Number.isInteger(n)&&Math.abs(n)<=100)operandA=n===0?0:n;else e.value=operandA;selectedExamples[1]='arithmetic';});
 update('operandB',e=>{const n=Number(e.value);if(e.value.trim()&&Number.isInteger(n)&&n!==0&&Math.abs(n)<=100)operandB=n;else e.value=operandB;selectedExamples[1]='arithmetic';});
 update('truthA',e=>{truthA=Number(e.value);});update('truthB',e=>{truthB=Number(e.value);});
 update('score',e=>{score=Number(e.value);selectedExamples[2]='selection';const article=$('flowchart');if(article){const existing=article.querySelector('svg');if(existing)existing.remove();article.insertAdjacentHTML('beforeend',flowchart());}});
 update('limit',e=>{const n=Number(e.value);if(e.value.trim()&&Number.isInteger(n)&&n>=0&&n<=10){limit=n;loopStep=0;}selectedExamples[3]='loops';});
}
function reference(){
 const selected=program();
 return `<section class="hero"><h1>${esc(u('reference'))}</h1><p class="lede">${esc(u('referenceIntro'))}</p><div class="controls"><span class="tag">${esc(selected.label)} · ${esc(selected.requires)}</span><a class="button" href="#escapes">${esc(u('escapes'))}</a><a class="button" href="#formats">${esc(u('formats'))}</a></div></section><div id="labMount"></div><section id="escapes" class="reference-section"><h2>${esc(u('escapes'))}</h2><p>${rich(u('aboutEscapes'))}</p><div class="table-wrap"><table><thead><tr><th scope="col">${esc(selected.label)}</th><th scope="col">${esc(u('meaning'))}</th></tr></thead><tbody>${selected.escapes.map((token,i)=>`<tr><td><code dir="ltr">${esc(token)}</code></td><td>${esc(tr().escapeNames[i])}</td></tr>`).join('')}</tbody></table></div></section><section id="formats" class="reference-section"><h2>${esc(u('formats'))}</h2><p>${rich(u('aboutFormats'))}</p><p class="notice">${rich(u('caution'))}</p><div class="table-wrap"><table><thead><tr><th scope="col">${esc(u('meaning'))}</th><th scope="col">${esc(u('output'))} · ${esc(selected.label)}</th><th scope="col">${esc(u('input'))} · ${esc(selected.label)}</th></tr></thead><tbody>${selected.formats.map(([index,output,input])=>`<tr><td>${esc(tr().formatNames[index])}</td><td><code dir="ltr">${esc(output)}</code></td><td><code dir="ltr">${esc(input)}</code></td></tr>`).join('')}</tbody></table></div><p>${rich(u('precision'))}</p><p>${rich(u('safeInput'))}</p>${fullExample('input',u('input'))}${fullExample('memory',tr().topics[10][0])}</section>${exercise(4)}<a class="button" href="${pageLink('index.html')}">← ${esc(u('home'))}</a>${footer()}`;
}

function moduleFromHash(){const hash=location.hash.slice(1);if(hash==='functions'||/^functions-(?:[1-8]|quiz|practice)$/.test(hash))return 7;if(hash==='pointers'||/^pointers-(?:[1-5]|simulation|quiz|practice)$/.test(hash))return 8;if(hash==='oop'||/^oop-(?:[1-7]|public|private|protected|quiz|practice|guidance|example)$/.test(hash))return 9;if(hash==='file-handling'||/^file-handling-(?:[1-4]|example|safety|quiz|practice)$/.test(hash))return 10;if(hash==='exception-handling'||/^exception-handling-(?:[1-4]|example|quiz|practice)$/.test(hash))return 11;if(hash==='unit-testing'||/^unit-testing-(?:[1-5]|example|quiz|practice)$/.test(hash))return 12;if(['switch','switch-quiz'].includes(hash))return 2;if(['arrays','arrays-simulation','arrays-tutorial','arrays-quiz','arrays-practice'].includes(hash))return 6;if(['for-simulation','for-tutorial-title','for-quiz','for-practice'].includes(hash))return 3;const m=names.indexOf(hash);if(m!==-1)return m;const t=D.topics.indexOf(hash);return t<0?-1:groups.findIndex(([start,end])=>t>=start&&t<end);}
function enhanceLessonOutline(){document.querySelectorAll('.module-outline').forEach(nav=>{const links=[...nav.querySelectorAll('a[href^="#"]')].map(link=>({link,section:document.getElementById(link.hash.slice(1))})).filter(item=>item.section);if(!links.length)return;const progress=document.createElement('div');progress.className='lesson-progress';progress.innerHTML='<span>Lesson progress</span><progress max="'+links.length+'" value="0" aria-label="Current position in lesson"></progress><span class="lesson-progress-count" aria-live="polite"></span>';nav.insertAdjacentElement('afterend',progress);const update=index=>{links.forEach((item,i)=>{if(i===index)item.link.setAttribute('aria-current','step');else item.link.removeAttribute('aria-current');});progress.querySelector('progress').value=index+1;progress.querySelector('.lesson-progress-count').textContent=`Section ${index+1} of ${links.length}`;};if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>a.boundingClientRect.top-b.boundingClientRect.top);if(visible.length){const index=links.findIndex(item=>item.section===visible[0].target);if(index!==-1)update(index);}}, {rootMargin:'-18% 0px -68% 0px'});links.forEach(item=>observer.observe(item.section));}nav.addEventListener('click',event=>{const link=event.target.closest('a');const index=links.findIndex(item=>item.link===link);if(index!==-1)update(index);});update(0);});}
function assignmentStarter(){const lines={c:['#include <stdio.h>','','int main(void) {','    /* TODO: implement the assignment */','    return 0;','}'],cpp:['#include <iostream>','','int main() {','    // TODO: implement the assignment','    return 0;','}'],python:['# TODO: implement the assignment'],java:['public class Main {','    public static void main(String[] args) {','        // TODO: implement the assignment','    }','}'],javascript:["'use strict';",'','// TODO: implement the assignment'],csharp:['using System;','','class Program {','    static void Main() {','        // TODO: implement the assignment','    }','}']};return lines[codeLanguage].join('\n');}
function assignmentMarkup(id,assignment,target){const labels=window.LESSON_ASSIGNMENT_LABELS[language]||window.LESSON_ASSIGNMENT_LABELS.en;const title=target.querySelector('h1,h2,h3,h4')?.textContent.trim()||id;return `<div class="topic-assignment" data-topic-assignment="${esc(id)}" lang="en" dir="ltr"><p class="eyebrow">${esc(labels.title)}</p><p><strong>${esc(labels.task)}:</strong> ${esc(assignment.task)}</p><h3>${esc(labels.expected)}</h3><pre class="assignment-expected">${esc(assignment.expected)}</pre><div class="controls"><button type="button" class="primary" data-assignment-run="${esc(id)}" data-assignment-title="${esc(title)}">${esc(labels.open)} →</button><span class="small">${esc(labels.note)}</span></div></div>`;}
function enhanceTopicAssignments(){const assignments=window.LESSON_ASSIGNMENTS;if(!assignments)return;for(const [id,assignment] of Object.entries(assignments)){const target=document.getElementById(id);if(!target||target.querySelector(':scope > [data-topic-assignment]'))continue;target.insertAdjacentHTML('beforeend',assignmentMarkup(id,assignment,target));}}
function render(){const opened=[...document.querySelectorAll('details')].map((el,i)=>el.open?i:-1);if(!isReference)module=moduleFromHash();M.configure({language,codeLanguage,program:program(),topics:tr().topics,ids:D.topics});renderShell();$('content').innerHTML=isReference?reference():module<0?overview():module===12?unitTestingLesson()+footer():module===11?exceptionHandlingLesson()+footer():module===10?fileHandlingLesson()+footer():module===9?oopLesson()+footer():module===8?pointersLesson()+footer():module===7?functionsLesson()+footer():module===6?arrayLesson()+footer():modulePage();renderLab();if(module===12&&!isReference)window.UnitTestingLesson?.mount();if(module===11&&!isReference)window.ExceptionHandlingLesson?.mount();if(module===10&&!isReference)window.FileHandlingLesson?.mount();if(module===9&&!isReference)window.OOPLesson?.mount();if(module===8&&!isReference)window.PointersLesson?.mount();if(module===7&&!isReference)window.FunctionsLesson?.mount();if(module===2&&!isReference)window.SwitchLesson?.mount();if(module===6&&!isReference)window.ArraysLesson?.mount();if(module===3&&!isReference)window.ForLesson?.mount();if(module===0&&!isReference)M.mount();enhanceLessonOutline();enhanceTopicAssignments();[...document.querySelectorAll('details')].forEach((el,i)=>{el.open=opened.includes(i);});$('status').textContent='';}
function scrollToHash(){const id=location.hash.slice(1);const target=document.getElementById(id);if(target)target.scrollIntoView?.({block:'start'});else window.scrollTo?.({top:0});}
window.addEventListener('hashchange',()=>{render();scrollToHash();});
document.addEventListener('click',async e=>{
 if(e.target.closest('#skip')){e.preventDefault();$('content').setAttribute('tabindex','-1');$('content').focus();$('content').scrollIntoView?.({block:'start'});return;}
 const b=e.target.closest('button');if(!b)return;
 if(b.dataset.assignmentRun){const id=b.dataset.assignmentRun,assignment=window.LESSON_ASSIGNMENTS[id];if(!assignment)throw new Error('Missing coding assignment: '+id);window.CodeRunner.open({language,codeLanguage,filename:filename('assignment'),code:assignmentStarter(),stdin:assignment.stdin,label:'Assignment · '+b.dataset.assignmentTitle});return;}
 if(b.dataset.run){const id=b.dataset.run==='current'?currentId():b.dataset.run;window.CodeRunner.open({language,codeLanguage,filename:filename(id),code:b.dataset.run==='current'?currentCode(id):E[id].code,stdin:E[id].stdin||'',label:program().label});return;}
 const action=b.dataset.action;
 if(action==='print'){window.print();return;}
 if(action==='step'){if(module===0)helloStep=Math.min(2,helloStep+1);else if(module===3){loopStep=Math.min(limit,loopStep+1);selectedExamples[3]='loops';}renderLab();$('labMount').querySelector('[data-action="step"]')?.focus();}
 if(action==='reset'){if(isReference)revealed=false;else if(module===0)helloStep=0;else if(module===1){operandA=7;operandB=2;selectedExamples[1]='arithmetic';}else if(module===3){loopStep=0;selectedExamples[3]='loops';}renderLab();$('labMount').querySelector('[data-action="reset"]')?.focus();}
 if(action==='reveal'){revealed=true;renderLab();$('labMount').querySelector('[data-action="reveal"]')?.focus();}
 if(b.dataset.copy){const id=b.dataset.copy;const code=id==='current'?currentCode(currentId()):E[id].code;try{await navigator.clipboard.writeText(code);$('status').textContent=u('copied');b.textContent=u('copied');}catch{$('status').textContent=u('copyFailed');}}
 if(b.dataset.download){const id=b.dataset.download==='current'?currentId():b.dataset.download;const code=b.dataset.download==='current'?currentCode(id):E[id].code;const blob=new Blob([code],{type:'text/plain;charset=utf-8'});const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download=filename(id);document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(href),1000);}
});
render();if(location.hash)setTimeout(scrollToHash,0);
// Expose pure state snapshots for deterministic educational checks.
window.courseState=()=>({language,codeLanguage,module,helloStep,operandA,operandB,truthA,truthB,score,limit,loopStep,demo,revealed});
})();
