'use strict';
(() => {
const D=window.COURSE_DATA,E=window.C_EXAMPLES;
const SITE_TITLE='Learn programming with Visualization';
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rich=s=>esc(s).replace(/`([^`]+)`/g,'<code dir="ltr">$1</code>');
const groups=[[0,8],[8,15],[15,23],[23,29]], names=['intro','data','control','module-loops'];
const isReference=document.body.dataset.page==='reference';
let language='da';
try{const saved=localStorage.getItem('ds-language');if(D.locales[saved])language=saved;}catch{}
const urlLang=new URLSearchParams(location.search).get('lang');if(D.locales[urlLang])language=urlLang;
let module=-1,helloStep=0,operandA=7,operandB=2,truthA=1,truthB=0,score=72,limit=5,loopStep=0,demo=0,revealed=false;
let selectedExamples=['hello','arithmetic','selection','loops'];
const tr=()=>D.translations[language];
const u=key=>{if(!(key in tr().ui))throw new Error('Missing translation: '+key);return tr().ui[key];};
const link=path=>path+(path.includes('?')?'&':'?')+'lang='+encodeURIComponent(language);
function pageLink(path,hash=''){return link(path)+(hash?'#'+hash:'');}
function topicLink(i){return pageLink('index.html',D.topics[i]);}
function btn(key,action,extra=''){return `<button type="button" data-action="${action}" ${extra}>${esc(u(key))}</button>`;}
function codeButtons(id){return `<div class="controls"><button type="button" data-copy="${id}">${esc(u('copy'))}</button><button type="button" data-download="${id}">${esc(u('download'))}</button></div>`;}
function fullExample(id,title){const ex=E[id];return `<details class="sample"><summary>${esc(u('code'))} · ${esc(title)}</summary>${codeButtons(id)}<pre tabindex="0" dir="ltr"><code>${esc(ex.code)}</code></pre>${ex.stdin?`<p class="small">${esc(u('input'))}</p><pre class="output" dir="ltr">${esc(ex.stdin)}</pre>`:''}${ex.output?`<p class="small">${esc(u('output'))}</p><pre class="output" dir="ltr">${esc(ex.output)}</pre>`:''}</details>`;}
function exercise(index){return `<section class="exercise"><h2>${esc(u('exercise'))}</h2><p>${esc(tr().questions[index])}</p><details><summary>${esc(u('answer'))}</summary><p>${esc(tr().answers[index])}</p></details></section>`;}
function footer(){return `<footer class="foot"><p>${esc(u('codeNote'))}</p><a href="https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf" target="_blank" rel="noopener">${esc(u('source'))}</a></footer>`;}
function referenceCallout(){return `<section class="callout"><div><h2>${esc(u('reference'))}</h2><p class="small">${esc(u('referenceIntro'))}</p></div><a class="button primary" href="${pageLink('c-formatting.html')}">${esc(u('open'))} →</a></section>`;}
function renderShell(){
 document.documentElement.lang=language==='zh'?'zh-Hans':language;
 document.documentElement.dir=['ar','ur'].includes(language)?'rtl':'ltr';
 document.title=(isReference?u('reference'):module<0?SITE_TITLE:tr().modules[module])+' · CodeViz';
 $('skip').textContent=u('skip');
 $('sidebar').innerHTML=`<a class="brand" href="${pageLink('index.html')}"><span aria-hidden="true">&lt;/&gt;</span>CodeViz</a><p class="aside-note">C11 · 4 ${esc(u('module'))} · 29 ${esc(u('topics'))}</p><nav aria-label="${esc(u('topics'))}"><a href="${pageLink('index.html')}" ${!isReference&&module<0?'aria-current="page"':''}><b>⌂</b>${esc(u('home'))}</a>${names.map((n,i)=>`<a href="${pageLink('index.html',n)}" ${!isReference&&module===i?'aria-current="page"':''}><b>0${i+1}</b>${esc(tr().modules[i])}</a>`).join('')}</nav><nav class="nav-other" aria-label="${esc(u('reference'))}"><a href="${pageLink('c-formatting.html')}" ${isReference?'aria-current="page"':''}><b>↳</b>${esc(u('reference'))}</a><a href="${pageLink('datastrukturer.html')}"><b>↗</b>${esc(u('structures'))}</a></nav>`;
 $('top').innerHTML=`<span class="eyebrow">C · ${esc(u('home'))}</span><div class="controls"><label for="language">${esc(u('language'))}</label><select id="language">${Object.entries(D.locales).map(([k,v])=>`<option value="${k}" ${k===language?'selected':''}>${esc(v)}</option>`).join('')}</select>${btn('print','print')}</div>`;
 $('language').addEventListener('change',e=>{
   language=e.target.value;
   try{localStorage.setItem('ds-language',language);}catch{}
   try{const url=new URL(location.href);url.searchParams.set('lang',language);history.replaceState(null,'',url);}catch{}
   render();
 });
}
function overview(){return `<section class="hero"><div class="eyebrow">C11 · 01—04</div><h1>${esc(SITE_TITLE)}</h1><p class="lede">${esc(u('intro'))}</p><div class="tags"><span class="tag">4 ${esc(u('module'))}</span><span class="tag">29 ${esc(u('topics'))}</span><span class="tag">10 ${esc(u('language'))}</span><span class="tag">C11</span></div></section><section aria-label="${esc(u('allTopics'))}" class="cards">${groups.map(([start,end],m)=>`<article class="card"><span class="number">0${m+1}</span><h2>${esc(tr().modules[m])}</h2><ol>${tr().topics.slice(start,end).map(([title],j)=>`<li><a href="${topicLink(start+j)}">${esc(title)}</a></li>`).join('')}</ol><a class="button" href="${pageLink('index.html',names[m])}">${esc(u('open'))} →</a></article>`).join('')}</section>${referenceCallout()}<a class="button" href="${pageLink('datastrukturer.html')}">${esc(u('structures'))} →</a>${footer()}`;}
const topicExamples={6:'hello',8:'memory',11:'input',13:'arithmetic',17:'truth',21:'selection',22:'assignment',24:'loops',25:'sentinel',26:'jump',27:'increment',28:'while'};
function modulePage(){const [start,end]=groups[module];return `<section class="hero"><div class="eyebrow">${esc(u('module'))} 0${module+1}</div><h1>${esc(tr().modules[module])}</h1><p class="lede">${esc(u('intro'))}</p></section><div id="labMount"></div><section class="lessons" aria-label="${esc(u('topics'))}">${tr().topics.slice(start,end).map(([title,body],j)=>{const i=start+j,id=D.topics[i];let extra='';if(i===5)extra='<pre class="output" dir="ltr"><code>gcc -std=c11 -Wall -Wextra -Wpedantic hello.c -o hello\n./hello</code></pre>';if(i===7)extra=`<a class="button primary" href="${pageLink('c-formatting.html')}">${esc(u('reference'))} →</a>`;if(i===10)extra=`<p class="notice">${esc(u('memoryNote'))}</p>`;if(i===11)extra=`<p class="notice">${rich(u('safeInput'))}</p>`;if(i===20)extra=flowchart();return `<article class="lesson" id="${id}"><span class="topic-no">${module+1}.${j+1}</span><h2><a href="#${id}">${esc(title)}</a></h2><p>${rich(body)}</p>${extra}${topicExamples[i]?fullExample(topicExamples[i],title):''}</article>`;}).join('')}</section>${exercise(module)}${module===0||module===1?referenceCallout():''}<div class="pager">${module>0?`<a class="button" href="${pageLink('index.html',names[module-1])}">← ${esc(tr().modules[module-1])}</a>`:`<a class="button" href="${pageLink('index.html')}">← ${esc(u('home'))}</a>`}${module<3?`<a class="button primary" href="${pageLink('index.html',names[module+1])}">${esc(tr().modules[module+1])} →</a>`:''}</div>${footer()}`;}
function flowchart(){const pass=score>=50;return `<svg class="flow" viewBox="0 0 400 360" role="img" aria-label="${esc(tr().topics[20][0]+': '+u('score')+' >= 50')}"><defs><marker id="arrow-${module}" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6" fill="#7187a1"/></marker></defs><g class="arrow" marker-end="url(#arrow-${module})"><path d="M200 48 V75"/><path d="M200 161 V183 H95 V215"/><path d="M200 161 V183 H305 V215"/><path d="M95 255 V296 H200 V313"/><path d="M305 255 V296 H200"/></g><rect class="node" x="150" y="8" width="100" height="40" rx="20"/><text x="200" y="34" text-anchor="middle">${esc(u('start'))}</text><polygon class="decision" points="200,75 287,118 200,161 113,118"/><text x="200" y="123" text-anchor="middle">score ≥ 50?</text><text x="92" y="203" text-anchor="middle">${esc(u('true'))}</text><text x="308" y="203" text-anchor="middle">${esc(u('false'))}</text><rect class="node ${pass?'active-node':''}" x="25" y="215" width="140" height="40" rx="4"/><text x="95" y="241" text-anchor="middle">${esc(u('pass'))}</text><rect class="node ${!pass?'active-node':''}" x="235" y="215" width="140" height="40" rx="4"/><text x="305" y="241" text-anchor="middle">${esc(u('retry'))}</text><rect class="node" x="150" y="313" width="100" height="40" rx="20"/><text x="200" y="339" text-anchor="middle">${esc(u('end'))}</text></svg>`;}
function currentCode(id){let code=E[id].code;
 if(id==='arithmetic')code=code.replace('int a = 7, b = 2;',`int a = ${operandA}, b = ${operandB};`).replace('double / :','7.0 / 2 =').replace('(double)a / b','7.0 / 2');
 if(id==='selection')code=code.replace('int score = 72;',`int score = ${score};`);
 if(id==='loops')code=code.replace('int n = 5;',`int n = ${limit};`);
 return code;
}
function currentId(){return isReference?'format'+demo:selectedExamples[module];}
function codePane(){const id=currentId();
 const lines=currentCode(id).trimEnd().split('\n');return `<div class="code-pane"><div class="code-head"><h3>${esc(u('code'))} · ${esc(id)}.c</h3>${codeButtons('current')}</div><pre id="codeView" tabindex="0" dir="ltr"><code>${lines.map((line,i)=>`<span class="code-line ${module===0&&!isReference&&i===[0,2,3,4,5][helloStep]?'active':''}"><span class="line-num">${i+1}</span>${esc(line)||' '}</span>`).join('')}</code></pre><p class="small">${esc(u('codeNote'))}</p></div>`;
}
function arithmeticResult(){if(!validOperands())return u('rangeError');return `+ : ${operandA+operandB}\n- : ${operandA-operandB}\n* : ${operandA*operandB}\n/ : ${Math.trunc(operandA/operandB)}\n% : ${operandA%operandB}\n7.0 / 2 = 3.50\n2 + 3 * 4 = 14\n(2 + 3) * 4 = 20\n`;}
function validOperands(){return [operandA,operandB].every(x=>Number.isInteger(x)&&Math.abs(x)<=100)&&operandB!==0;}
function truthTable(){return `<div class="table-wrap"><table class="truth-table"><caption>${esc(tr().topics[17][0])}</caption><thead><tr>${['a','b','a && b','a || b','!a'].map(s=>`<th scope="col"><code>${esc(s)}</code></th>`).join('')}</tr></thead><tbody>${[[0,0],[0,1],[1,0],[1,1]].map(([a,b])=>`<tr class="${a===truthA&&b===truthB?'chosen':''}"><td>${a}</td><td>${b}</td><td>${a&&b?1:0}</td><td>${a||b?1:0}</td><td>${a?0:1}</td></tr>`).join('')}</tbody></table></div>`;}
function stage(){
 if(isReference)return `<label for="demoSelect">${esc(u('select'))}</label><select id="demoSelect" dir="ltr">${Object.keys(E).filter(k=>k.startsWith('format')).map((k,i)=>`<option value="${i}" ${i===demo?'selected':''}>${esc(E[k].label)}</option>`).join('')}</select><p>${esc(tr().topics[7][1].replace(/`/g,''))}</p><div class="controls">${btn('reveal','reveal','class="primary"')}${btn('reset','reset')}</div><h3>${esc(u('output'))}</h3><div id="demoOutput" aria-live="polite">${revealed?`<pre class="output" dir="ltr">${esc(E[currentId()].output)}</pre>`:`<div class="placeholder">${esc(u('reveal'))} →</div>`}</div>`;
 if(module===0)return `<p class="eyebrow">Hello, world!</p><div class="metrics"><div class="metric"><span>${esc(u('next'))}</span><strong>${helloStep+1} / 5</strong></div></div><p>${rich(tr().topics[6][1])}</p><div class="controls">${btn('next','step',`class="primary" ${helloStep===4?'disabled':''}`)}${btn('reset','reset')}</div><h3>${esc(u('output'))}</h3><pre class="output" dir="ltr" aria-live="polite">${helloStep>=2?'Hello, world!\n':'—'}</pre>`;
 if(module===1)return `<p>${rich(tr().topics[13][1])}</p><div class="controls"><label for="operandA">a</label><input id="operandA" type="number" min="-100" max="100" step="1" value="${operandA}"><label for="operandB">b</label><input id="operandB" type="number" min="-100" max="100" step="1" value="${operandB}">${btn('reset','reset')}</div><p class="small">${esc(u('rangeError'))}</p><h3>${esc(u('output'))}</h3><pre id="arithmeticOutput" class="output" dir="ltr" aria-live="polite">${esc(arithmeticResult())}</pre><p class="small">${esc(u('memoryNote'))}</p>`;
 if(module===2)return `<div class="controls"><label for="truthA">a</label><select id="truthA">${[0,1].map(n=>`<option value="${n}" ${truthA===n?'selected':''}>${n} · ${esc(u(n?'true':'false'))}</option>`).join('')}</select><label for="truthB">b</label><select id="truthB">${[0,1].map(n=>`<option value="${n}" ${truthB===n?'selected':''}>${n} · ${esc(u(n?'true':'false'))}</option>`).join('')}</select></div>${truthTable()}<div class="controls"><label for="score">${esc(u('score'))}</label><input id="score" type="range" min="0" max="100" value="${score}"><output for="score">${score}</output></div><p class="notice" aria-live="polite"><code dir="ltr">score >= 50 → ${score>=50?1:0}</code> · ${esc(u(score>=50?'pass':'retry'))}</p>`;
 return `<label for="limit">${esc(u('limit'))}</label><input id="limit" type="number" min="0" max="10" step="1" value="${limit}"><div class="metrics"><div class="metric"><span>${esc(u('iteration'))}</span><strong>${loopStep} / ${limit}</strong></div><div class="metric"><span>${esc(u('total'))}</span><strong>${loopStep*(loopStep+1)/2}</strong></div></div><div class="trace">${Array.from({length:limit},(_,i)=>`<span class="${i+1===loopStep?'current':i<loopStep?'done':''}">${i+1}</span>`).join('')}</div><div class="controls">${btn('next','step',`class="primary" ${loopStep>=limit?'disabled':''}`)}${btn('reset','reset')}</div><h3>${esc(u('output'))}</h3><pre class="output" dir="ltr" aria-live="polite">${Array.from({length:loopStep},(_,i)=>`i = ${i+1}, total = ${(i+1)*(i+2)/2}`).join('\n')||'—'}</pre><p class="small">${loopStep>=limit?esc(u('complete')):esc(tr().topics[24][0])}</p>`;
}
function renderLab(){const target=$('labMount');if(!target)return;target.innerHTML=`<section class="lab" aria-label="${esc(u('lab'))}"><div class="lab-head"><h2>${esc(u('lab'))}</h2><p class="small">${esc(u('labNote'))}</p></div><div class="lab-grid"><div class="stage">${stage()}</div>${codePane()}</div></section>`;
 const update=(id,cb)=>{const el=$(id);if(el)el.addEventListener('change',()=>{cb(el);renderLab();$(id)?.focus();});};
 update('demoSelect',e=>{demo=Number(e.value);revealed=false;});
 
 update('operandA',e=>{const n=Number(e.value);if(e.value.trim()&&Number.isInteger(n)&&Math.abs(n)<=100)operandA=n;else e.value=operandA;selectedExamples[1]='arithmetic';});
 update('operandB',e=>{const n=Number(e.value);if(e.value.trim()&&Number.isInteger(n)&&n!==0&&Math.abs(n)<=100)operandB=n;else e.value=operandB;selectedExamples[1]='arithmetic';});
 update('truthA',e=>{truthA=Number(e.value);});update('truthB',e=>{truthB=Number(e.value);});
 update('score',e=>{score=Number(e.value);selectedExamples[2]='selection';const article=$('flowchart');if(article){const existing=article.querySelector('svg');if(existing)existing.remove();article.insertAdjacentHTML('beforeend',flowchart());}});
 update('limit',e=>{const n=Number(e.value);if(e.value.trim()&&Number.isInteger(n)&&n>=0&&n<=10){limit=n;loopStep=0;}selectedExamples[3]='loops';});
}
const escapes=['\\n','\\t','\\v','\\\\',"\\'",'\\"','\\0','\\a','\\b','\\r','\\f','\\?'];
const escapeExamples=['"Hello\\nC"','"Name\\tAge"','"A\\vB"','"C:\\\\data"',"'\\\''",'"\\"C\\""',"'\\0'",'"\\a"','"A\\bB"','"A\\rB"','"A\\fB"','"\\?"'];
const formats=[['%d / %i','int','int *'],['%u','unsigned int','unsigned int *'],['%ld','long','long *'],['%lld','long long','long long *'],['%zu','size_t','size_t *'],['%f','double','float *'],['%lf','double','double *'],['%e / %g','double','float *'],['%Lf','long double','long double *'],['%c','int','char *'],['%s','char *','char *'],['%x / %o','unsigned int','unsigned int *'],['%p','void *','void **'],['%%','—','—']];
function reference(){return `<section class="hero"><div class="eyebrow">C11 · printf / scanf</div><h1>${esc(u('reference'))}</h1><p class="lede">${esc(u('referenceIntro'))}</p><div class="controls"><a class="button" href="#escapes">${esc(u('escapes'))}</a><a class="button" href="#formats">${esc(u('formats'))}</a></div></section><div id="labMount"></div><section id="escapes" class="reference-section"><h2>${esc(u('escapes'))}</h2><p>${rich(u('aboutEscapes'))}</p><div class="table-wrap"><table><thead><tr><th scope="col">C</th><th scope="col">${esc(u('meaning'))}</th><th scope="col">${esc(u('example'))}</th></tr></thead><tbody>${escapes.map((s,i)=>`<tr><td><code dir="ltr">${esc(s)}</code></td><td>${esc(tr().escapeNames[i])}</td><td><code dir="ltr">${esc(escapeExamples[i])}</code></td></tr>`).join('')}</tbody></table></div></section><section id="formats" class="reference-section"><h2>${esc(u('formats'))}</h2><p>${rich(u('aboutFormats'))}</p><p class="notice">${rich(u('caution'))}</p><div class="table-wrap"><table><thead><tr><th scope="col">C</th><th scope="col">${esc(u('meaning'))}</th><th scope="col"><code>printf</code> · ${esc(u('type'))}</th><th scope="col"><code>scanf</code> · ${esc(u('type'))}</th></tr></thead><tbody>${formats.map(([f,p,s],i)=>`<tr><td><code dir="ltr">${esc(f)}</code></td><td>${esc(tr().formatNames[i])}</td><td><code dir="ltr">${esc(p)}</code></td><td><code dir="ltr">${esc(s)}</code></td></tr>`).join('')}</tbody></table></div><p>${rich(u('precision'))}</p><p>${rich(u('safeInput'))}</p>${fullExample('input',u('input'))}${fullExample('memory',tr().topics[10][0])}</section>${exercise(4)}<a class="button" href="${pageLink('index.html')}">← ${esc(u('home'))}</a>${footer()}`;}
function moduleFromHash(){const hash=location.hash.slice(1);const m=names.indexOf(hash);if(m!==-1)return m;const t=D.topics.indexOf(hash);return t<0?-1:groups.findIndex(([start,end])=>t>=start&&t<end);}
function render(){const opened=[...document.querySelectorAll('details')].map((el,i)=>el.open?i:-1);if(!isReference)module=moduleFromHash();renderShell();$('content').innerHTML=isReference?reference():module<0?overview():modulePage();renderLab();[...document.querySelectorAll('details')].forEach((el,i)=>{el.open=opened.includes(i);});$('status').textContent='';}
function scrollToHash(){const id=location.hash.slice(1);const target=document.getElementById(id);if(target)target.scrollIntoView?.({block:'start'});else window.scrollTo?.({top:0});}
window.addEventListener('hashchange',()=>{render();scrollToHash();});
document.addEventListener('click',async e=>{
 if(e.target.closest('#skip')){e.preventDefault();$('content').setAttribute('tabindex','-1');$('content').focus();$('content').scrollIntoView?.({block:'start'});return;}
 const b=e.target.closest('button');if(!b)return;
 const action=b.dataset.action;
 if(action==='print'){window.print();return;}
 if(action==='step'){if(module===0)helloStep=Math.min(4,helloStep+1);else if(module===3){loopStep=Math.min(limit,loopStep+1);selectedExamples[3]='loops';}renderLab();$('labMount').querySelector('[data-action="step"]')?.focus();}
 if(action==='reset'){if(isReference)revealed=false;else if(module===0)helloStep=0;else if(module===1){operandA=7;operandB=2;selectedExamples[1]='arithmetic';}else if(module===3){loopStep=0;selectedExamples[3]='loops';}renderLab();$('labMount').querySelector('[data-action="reset"]')?.focus();}
 if(action==='reveal'){revealed=true;renderLab();$('labMount').querySelector('[data-action="reveal"]')?.focus();}
 if(b.dataset.copy){const id=b.dataset.copy;const code=id==='current'?currentCode(currentId()):E[id].code;try{await navigator.clipboard.writeText(code);$('status').textContent=u('copied');b.textContent=u('copied');}catch{$('status').textContent=u('copyFailed');}}
 if(b.dataset.download){const id=b.dataset.download==='current'?currentId():b.dataset.download;const code=b.dataset.download==='current'?currentCode(id):E[id].code;const blob=new Blob([code],{type:'text/x-c;charset=utf-8'});const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download=id+'.c';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(href),1000);}
});
render();if(location.hash)setTimeout(scrollToHash,0);
// Expose pure state snapshots for deterministic educational checks.
window.courseState=()=>({language,module,helloStep,operandA,operandB,truthA,truthB,score,limit,loopStep,demo,revealed});
})();
