'use strict';
(() => {
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const S={hardware:0,root:81,trained:false,weight:150,temp:24,devices:100,rate:1};
let context;
const t=()=>window.MODULE_ONE_DATA[context.language];
const u=k=>t().ui[k];
const icon=(name)=>{const shapes={
 cpu:'<rect x="17" y="17" width="30" height="30" rx="5"/><path d="M24 17V8m8 9V8m8 9V8M24 47v9m8-9v9m8-9v9M17 24H8m9 8H8m9 8H8m39-16h9m-9 8h9m-9 8h9"/><rect x="25" y="25" width="14" height="14" rx="2"/>',
 input:'<path d="M12 18h40v30H12zM20 25h4m6 0h4m6 0h4M20 33h4m6 0h4m6 0h4M20 41h24"/>',
 ram:'<rect x="9" y="18" width="46" height="27" rx="3"/><path d="M17 45v7m10-7v7m10-7v7m10-7v7M17 26h10v11H17zM36 26h10v11H36z"/>',
 output:'<rect x="8" y="11" width="48" height="34" rx="4"/><path d="M32 45v10m-13 0h26M18 23l7 6-7 6m14 0h12"/>',
 storage:'<rect x="13" y="9" width="38" height="46" rx="5"/><circle cx="32" cy="28" r="10"/><path d="m32 28 13 13m-24 6h4"/>',
 library:'<path d="M9 13h12v40H9zM25 9h12v44H25zM42 14l10-2 8 38-10 2zM12 23h6M28 20h6"/>',
 ai:'<circle cx="15" cy="17" r="5"/><circle cx="15" cy="47" r="5"/><circle cx="32" cy="32" r="6"/><circle cx="49" cy="17" r="5"/><circle cx="49" cy="47" r="5"/><path d="m19 20 9 8m-9 15 9-7m9-8 8-8m-8 16 8 8"/>',
 embedded:'<rect x="19" y="19" width="26" height="26" rx="4"/><path d="M25 19V9m14 10V9M25 45v10m14-10v10M19 25H9m10 14H9m36-14h10M45 39h10"/><circle cx="32" cy="32" r="5"/>',
 data:'<path d="M10 52h45M16 45V30h7v15M29 45V18h7v27M42 45V8h7v37"/>'};return `<svg viewBox="0 0 64 64" class="concept-icon" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">${shapes[name]||shapes.cpu}</svg>`;};
function hero(){return `<div class="module-intro"><div><p class="lede">${esc(t().lead)}</p><a class="button primary" href="#computers">${esc(u('explore'))} ↓</a></div><div class="machine-art" aria-hidden="true"><div class="orbit-small">01 · 10 · 11</div><div class="art-chip">${icon('cpu')}<span>CodeViz</span></div><div class="art-node art-a">${icon('input')}</div><div class="art-node art-b">${icon('ai')}</div><div class="art-node art-c">${icon('embedded')}</div><div class="art-node art-d">${icon('data')}</div><div class="orbit-small bottom">&lt; / &gt; → 0101</div></div></div><section class="learning-goals"><h2>${esc(u('goals'))}</h2><ol>${t().goals.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></section><nav class="module-outline" aria-label="${esc(u('outline'))}">${context.topics.slice(0,8).map(([title],i)=>`<a href="#${context.ids[i]}"><b>1.${i+1}</b>${esc(title)}</a>`).join('')}</nav>`;}
function extra(i){if(i<5)return `<div class="concept-grid">${t().cards[i].map(([title,body],j)=>`<section class="concept"><span class="concept-index">0${j+1}</span><h3>${esc(title)}</h3><p>${esc(body)}</p></section>`).join('')}</div><div class="case-study">${icon(['cpu','library','ai','embedded','data'][i])}<div><h3>${esc(u('case'))}</h3><p>${esc(t().cases[i])}</p></div></div><section class="concept-lab" aria-label="${esc(u('try')+' · '+context.topics[i][0])}"><div class="concept-lab-title"><h3>${esc(u('try'))}</h3><span class="tag">${esc(u('simulation'))}</span></div><div id="concept-${i}"></div></section><details class="knowledge-check"><summary>${esc(u('check'))} · ${esc(t().checks[i][0])}</summary><p>${esc(t().checks[i][1])}</p></details>`;
 if(i===5)return `<div class="build-route">${['source','build','execute'].map((k,j)=>`<div><b>0${j+1}</b><span>${esc(u(k))}</span><code>${esc(buildPath()[j])}</code></div>`).join('')}</div><p class="small">${esc(u('runNote'))}</p><section class="runner-callout"><h3>${esc(u('runner'))}</h3><p>${esc(u('runnerHint'))}</p><button class="primary" type="button" data-run="hello">▶ ${esc(u('openRunner'))}</button><p class="small">${esc(u('external'))}</p></section>`;
 if(i===6)return `<section class="anatomy"><h3>${esc(u('skeleton'))} · ${esc(context.program.label)}</h3><dl>${anatomy().map(([k,v])=>`<div><dt>${esc(u(k))}</dt><dd><code>${esc(v)}</code></dd></div>`).join('')}</dl></section><div id="labMount"></div>`;
 return '';
}
function buildPath(){const file=context.program.filename||'hello.'+context.program.ext;return {c:[file,'GCC → native','./hello'],cpp:[file,'G++ → native','./hello'],python:[file,'Python → bytecode','Python runtime'],java:[file,'javac → Main.class','JVM'],javascript:[file,'Node.js / V8','Node.js runtime'],csharp:[file,'dotnet → IL','.NET runtime']}[context.codeLanguage];}
function anatomy(){return {c:[['imports','#include <stdio.h>'],['entry','int main(void) {'],['statements','printf("Hello, world!\\n");'],['finish','return 0; }']],cpp:[['imports','#include <iostream>'],['entry','int main() {'],['statements','std::cout << "Hello, world!\\n";'],['finish','return 0; }']],python:[['imports','print → builtins'],['entry','hello.py → Python'],['statements','print("Hello, world!")'],['finish','EOF']],java:[['imports','java.lang.System → java.lang'],['entry','public static void main(String[] args) {'],['statements','System.out.println("Hello, world!");'],['finish','}']],javascript:[['imports','console → Node.js / browser'],['entry','hello.js → Node.js'],['statements','console.log("Hello, world!");'],['finish','EOF']],csharp:[['imports','using System;'],['entry','static void Main() {'],['statements','Console.WriteLine("Hello, world!");'],['finish','}']]}[context.codeLanguage];}
function hardware(){const steps=['input','ram','cpu','output','storage'],values=['7, 5','a = 7; b = 5','7 + 5 = 12','12','result.txt → 12'];return `<div class="hardware-flow" dir="ltr">${steps.map((k,i)=>`<div class="hardware-node ${S.hardware===i?'selected':''}" ${S.hardware===i?'aria-current="step"':''}>${icon(k)}<span dir="auto">${esc(u(k))}</span><code>${S.hardware>=i?values[i]:'—'}</code></div>`).join('')}</div><div class="controls"><button data-concept="hardware-next" ${S.hardware===4?'disabled':''}>${esc(u('next'))}</button><button data-concept="hardware-reset">${esc(u('reset'))}</button><output aria-live="polite">${S.hardware+1} / 5 · ${esc(u(steps[S.hardware]))}</output></div><p class="small">${esc(u('hardwareNote'))}</p>`;}
function library(){const calls={c:'sqrt('+S.root+'.0)',cpp:'std::sqrt('+S.root+'.0)',python:'math.sqrt('+S.root+')',java:'Math.sqrt('+S.root+'.0)',javascript:'Math.sqrt('+S.root+')',csharp:'Math.Sqrt('+S.root+'.0)'};const imp={c:'#include <math.h>',cpp:'#include <cmath>',python:'import math',java:'java.lang.Math',javascript:'Math',csharp:'using System;'};return `<div class="controls"><label for="root-value">${esc(u('argument'))}</label><input id="root-value" type="range" min="0" max="100" value="${S.root}"><output for="root-value">${S.root}</output></div><div class="function-route" dir="ltr"><div><span dir="auto">${esc(u('argument'))}</span><strong>${S.root}</strong></div><div>${icon('library')}<code>${esc(calls[context.codeLanguage])}</code></div><div><span dir="auto">${esc(u('result'))}</span><strong>${Number.isInteger(Math.sqrt(S.root))?'':'≈ '}${Number(Math.sqrt(S.root).toFixed(4))}</strong></div></div><p class="small"><code>${esc(imp[context.codeLanguage])}</code> · ${esc(context.program.label)}</p>`;}
function ai(){const a=[110,130],o=[170,190];const mean=v=>v.reduce((x,y)=>x+y,0)/v.length;const am=mean(a),om=mean(o),mid=(am+om)/2;const winner=S.weight<=mid?'apple':'orange';const x=v=>40+(v-80)*3;return `<div class="training-chips"><span>${esc(u('apple'))}: 110 g, 130 g</span><span>${esc(u('orange'))}: 170 g, 190 g</span></div><div class="controls"><button class="primary" data-concept="train" ${S.trained?'disabled':''}>${esc(u('fit'))}</button><button data-concept="ai-reset">${esc(u('reset'))}</button></div><p class="model-readout" aria-live="polite">${S.trained?`${esc(u('learned'))}: ${am} g · ${om} g / ${esc(u('boundary'))}: ${mid} g`:esc(u('untrained'))}</p><label for="fruit-weight">${esc(u('weight'))}</label><input id="fruit-weight" type="range" min="80" max="220" value="${S.weight}"><output for="fruit-weight">${S.weight} g</output><svg class="fruit-chart" viewBox="0 0 500 145" role="img" aria-label="${esc(u('training'))}: 110, 130 / 170, 190. ${esc(u('weight'))}: ${S.weight}"><rect x="40" y="28" width="210" height="65" fill="#e0f3eb"/><rect x="250" y="28" width="210" height="65" fill="#fff0d9"/><path d="M40 95H460" stroke="#789"/>${[80,100,120,140,160,180,200,220].map(v=>`<text x="${x(v)}" y="119" text-anchor="middle">${v}</text>`).join('')}${a.map(v=>`<circle cx="${x(v)}" cy="60" r="8" fill="#147553"/>`).join('')}${o.map(v=>`<rect x="${x(v)-7}" y="53" width="14" height="14" fill="#af5910"/>`).join('')}${S.trained?`<path d="M250 20V95" stroke="#536578" stroke-dasharray="4"/>`:''}<path d="M${x(S.weight)} 14v73" stroke="#215ad7" stroke-width="3"/><circle cx="${x(S.weight)}" cy="14" r="5" fill="#215ad7"/></svg><p class="prediction" aria-live="polite">${esc(u('predict'))}: <strong>${S.trained?esc(u(winner)):'—'}</strong></p>`;}
function embedded(){const on=S.temp>=30;return `<div class="controls"><label for="sensor-temp">${esc(u('temperature'))}</label><input id="sensor-temp" type="range" min="0" max="50" value="${S.temp}"><output for="sensor-temp">${S.temp} °C</output></div><div class="feedback-loop"><div class="sensor-card">${icon('embedded')}<span>${esc(u('sensor'))}</span><strong>${S.temp} °C</strong></div><div class="decision-card"><span>${esc(u('decision'))}</span><code>temperature >= 30</code><strong>${on?'true':'false'}</strong></div><div class="fan-card ${on?'is-on':''}"><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="45" fill="none" stroke="currentColor" stroke-width="3"/><g class="fan-blades" fill="currentColor"><path d="M50 49C18 17 58 0 59 28L53 49ZM50 49C82 17 100 58 72 59L51 53ZM50 50C82 82 41 100 40 72L47 51ZM50 50C18 82 0 41 28 40L49 47Z"/></g><circle cx="50" cy="50" r="6" fill="#152b40"/></svg><span>${esc(u('fan'))}</span><strong aria-live="polite">${esc(u(on?'on':'off'))}</strong></div></div><div class="feedback-arrow" aria-hidden="true">↺</div>`;}
function data(){const records=S.devices*S.rate*86400,bytes=records*16;const amount=bytes>=1e9?(bytes/1e9).toFixed(2)+' GB':(bytes/1e6).toFixed(2)+' MB';return `<div class="controls"><label for="data-devices">${esc(u('devices'))}</label><input id="data-devices" type="number" min="1" max="10000" step="1" value="${S.devices}"><label for="data-rate">${esc(u('rate'))}</label><select id="data-rate">${[1,10,100].map(n=>`<option value="${n}" ${n===S.rate?'selected':''}>${n}</option>`).join('')}</select></div><div class="data-metrics" aria-live="polite"><div><strong>${records.toLocaleString(context.language)}</strong><span>${esc(u('records'))}</span></div><div><strong>${amount}</strong><span>${esc(u('size'))}</span></div></div><div class="data-pipeline">${['collect','clean','analyse','decide'].map((k,i)=>`<div><span>0${i+1}</span><b>${esc(u(k))}</b></div>`).join('')}</div><p class="small">${esc(u('dataNote'))}</p>`;}
const widgets=[hardware,library,ai,embedded,data];
function draw(i){const el=document.getElementById('concept-'+i);if(el)el.innerHTML=widgets[i]();}
function mount(){widgets.forEach((_,i)=>draw(i));}
document.addEventListener('click',e=>{const b=e.target.closest('[data-concept]');if(!b)return;const a=b.dataset.concept;let i;if(a==='hardware-next'){S.hardware=Math.min(4,S.hardware+1);i=0;}if(a==='hardware-reset'){S.hardware=0;i=0;}if(a==='train'){S.trained=true;i=2;}if(a==='ai-reset'){S.trained=false;S.weight=150;i=2;}if(i!==undefined){draw(i);document.querySelector(`[data-concept="${a}"]`)?.focus();}});
document.addEventListener('change',e=>{const id=e.target.id,n=Number(e.target.value);let i;if(id==='root-value'){S.root=Math.min(100,Math.max(0,n));i=1;}if(id==='fruit-weight'){S.weight=Math.min(220,Math.max(80,n));i=2;}if(id==='sensor-temp'){S.temp=Math.min(50,Math.max(0,n));i=3;}if(id==='data-devices'){if(Number.isInteger(n)&&n>=1&&n<=10000)S.devices=n;i=4;}if(id==='data-rate'){if([1,10,100].includes(n))S.rate=n;i=4;}if(i!==undefined){draw(i);document.getElementById(id)?.focus();}});
window.ModuleOne={configure(c){context=c;},hero,extra,mount,ui:(language,key)=>window.MODULE_ONE_DATA[language].ui[key]};
})();
